# Generated by Django 3.2 on 2021-04-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.TextField(max_length=400)),
                ('experience', models.TextField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
