# Generated by Django 3.2 on 2021-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newweb', '0002_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='experience',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='careers',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
